version: '3.9'

services:
  db:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d statsbomb -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
       - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./new_data:/home/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=statsbomb
